name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      cache-key: test-file-key

    steps:
    - uses: actions/checkout@v3

    - name: test cache
      id: test-cache
      uses: actions/cache/restore@v3
      with:
        path: test-file
        key: ${{ env.cache-key }}

    - name: Check test file
      run: |
        [ -f test-file ] && cat test-file
        echo "TEST $GITHUB_RUN_ID" > test-file

    - name: Display test file
      run: cat test-file

    - name: Delete Previous Cache
      if: ${{ steps.test-cache.outputs.cache-hit }}
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete "${{ env.cache-key }}" --confirm

    - name: Save test cache
      uses: actions/cache/save@v3
      with:
        path: test-file
        key: ${{ env.cache-key }}
