name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: test cache
      id: test-cache
      uses: actions/cache/restore@v3
      with:
        path: test-file
        key: ${{ runner.os }}-test

    - name: Check test file
      run: |
        [ -f test-file ] && cat test-file
        echo "TEST $GITHUB_RUN_ID" > test-file

    - name: Display test file
      run: cat test-file

    - name: Save test cache
      uses: actions/cache/save@v3
      with:
        path: test-file
        key: ${{ steps.test-cache.outputs.cache-primary-key }}
