name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: test cache
      id: test
      uses: actions/cache@v3
      with:
        path: test-file
        key: ${{ runner.os }}-test

    - name: Check test file
      run: |
        [ -f test-file ] && cat test-file
        echo "TEST $GITHUB_RUN_ID" > test-file

    - name: Display test file
      run: cat test-file
